config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ru/ do 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :ads do
    member do
      put :status_new
      put :status_draft
      delete :delete_image
    end
    collection do
      get 'user_ads' => 'ads#user_ads', as: :user_ads
      get 'user_archive' => 'ads#user_archive', as: :user_archive
    end
  end
  resources :photos do
    get 'preview', on: :member
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "ads#index" 
end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user.present? && !user.admin?
      can [:create, :user_ads, :user_archive, :delete_image], Ad
      can :destroy, Ad, user_id: user.id
      can :update, Ad, user_id: user.id, status: [0, 2]
      can :status_new, Ad, user_id: user.id, status: [0, 2]
      can :status_draft, Ad, user_id: user.id, status: 5
    end
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description, against: %i[title description],
  using: {
    tsearch: { prefix: true }
  }

  def self.search(query)
    if query.present?
      search_by_title_and_description(query)
    else
      # No query? Return all records, newest first.
      order("created_at DESC")
    end
  end

  scope :new_ads, -> {
    where(status: 'new_ad')
  }

  validates :title, presence: true, length: { maximum: 15 }
  validates :description, :user_id, :ad_type_id, presence: true

  has_many_attached :images
  belongs_to :user
  belongs_to :ad_type

  enum status: %i[draft_ad new_ad canceled_ad approved_ad published_ad archived_ad]
  after_initialize do
    self.status ||= :draft_ad if self.new_record?
  end
end

app/models/ad_type.rb
class AdType < ApplicationRecord
  validates :name, uniqueness: true
  has_many :ads
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :read, :all
      can [:destroy, :update, :approve], Ad
      can [:create, :destroy, :update], User
      can [:create, :destroy], AdType
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, length: { minimum: 6 }, on: :create
  has_many :ads, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ad_types_controller.rb
class AdTypesController < ApplicationController
  load_and_authorize_resource
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  helper_method :sort_column, :sort_direction
  load_and_authorize_resource
  before_action :set_ad, only: [:show, :edit, :update, :destroy, :approve, :draft, :status_new]
  ActionController::Parameters.action_on_unpermitted_parameters = :raise

  def index
    @filter = Ad.ransack(params[:q])
    if params[:query]
      @ads = Ad.where(status: 4).search(params[:query]).includes(:user, :ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    else
      @ads = @filter.result.where(status: 4).includes(:user, :ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    end
  end

  def status_new
    @ad.update_attributes status: 1
    flash[:success] = 'Success! Ad will be published after admin approval.'
    redirect_to user_ads_ads_path
  end

  def status_draft
    @ad.update_attributes status: 0
    flash[:success] = 'The Ad was successfully converted to Draft Type.'
    redirect_to user_archive_ads_path
  end

  def user_ads
    @filter = Ad.ransack(params[:q])
    if params[:query]
      @ads = current_user.ads.where(status: [0, 1, 2, 3]).search(params[:query]).includes(:ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    else
      @ads = @filter.result.where(user_id: current_user.id, status: [0, 1, 2, 3]).includes(:ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10) 
    end
  end

  def user_archive
    @filter = Ad.ransack(params[:q])
    if params[:query]
      @ads = current_user.ads.where(status: 5).search(params[:query]).includes(:user, :ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    else
      @ads = @filter.result.where(user_id: current_user.id, status: 5).includes(:user, :ad_type).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10) 
    end
  end

  def delete_image
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @image.purge
    flash[:success] = 'Image were successfully deleted.'
    redirect_to edit_ad_path
  end

  def show
  end

  def new
    @ad = Ad.new
  end

  def edit
  end

  def create
    @ad = current_user.ads.new(ad_params)
    if @ad.save!
      flash[:success] = 'Ad was succesfully created! You can see it in Your ads list.'
      redirect_to user_ads_ads_path
    else
      flash[:warning] = "Something go wrong. Please, try again"
      render 'new'
    end
  end

  def update
    if @ad.update(ad_params)
      flash[:success] = 'The Ad was successfully updated!'
      redirect_to request.referrer
    else
      flash[:error] = 'Sorry, an error has occurred while updating'
      redirect_to request.referrer
    end
  end

  def destroy
    @ad.destroy
    flash[:success] = 'Ad was succesfully deleted.'
    redirect_to request.referrer
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
    @ad = Ad.with_attached_images.find(params[:id]) if @ad.images.attached?
  end

  def ad_params
    params.require(:ad).permit(:title, :description, :user_id, :status, :ad_type_id, images: [])
  end

  def sort_column
    Ad.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end

  def sort_direction
    params[:direction] || 'asc'
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  rescue_from CanCan::AccessDenied do 
    flash[:warning] = 'You have not permission to do this action'
    redirect_to main_app.root_path
  end
  rescue_from ActionController::UnpermittedParameters do
    flash[:warning] = 'You have not permission to update these params'
    redirect_to request.referrer
  end
  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Can not find this record. Please, try again'
    redirect_to main_app.root_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def set_locale 
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale}.merge options
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :current_password])
  end
end

app/helpers/ad_types_helper.rb
module AdTypesHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, sort: column, direction: direction
  end
end

app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::BootstrapLinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/views/ads/_form.html.slim
= simple_form_for @ad do |f|
          = f.label :title, t(:title)
          = f.input :title, label:false, required: true, placeholder: t(:title_placeholder)
          = f.input :description, label: t(:description), required: true, hint: t(:description_hint)
          = f.label :ad_type_id, t(:type_select)
          = f.input :ad_type_id, label: false, required: true, collection: AdType.all, prompt: t(:type_select_prompt)
          = f.file_field :images, multiple: true, class: "btn btn-primary btn-sm"
          - if @ad.images.attached?
            table.table.table-sm.table-bordered[style="margin-top: 20px"]
              thead
                tr
                  th.text-center
                    | Image
                  th.text-center
                    | Action
              tbody
                - @ad.images.each do |image|
                  tr
                    td.text-center
                      = image_tag image.variant(resize: "80x80")
                    td.text-center
                      = link_to 'Delete', delete_image_ad_path(@ad, image_id: image), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-sm btn-warning"  
            br
          .text-center[style="margin-top: 10px"]
            = f.button :submit, :class => "btn btn-lg btn-success"
            = link_to t(:back), user_ads_ads_path, class: "btn btn-lg btn-info"
            

app/views/ads/_results.html.slim
- unless @ads.empty?
  table.table.table-sm.table-bordered
    thead.thead-dark
      tr
        th.text-center
          = sortable 'title', t(:title)
        th.text-center
          = sortable 'description', t(:description)
        - unless params[:action] == "user_ads"  
          th.text-center
            = t(:email)
        th.text-center
          = sortable 'ad_type_id', t(:ad_type)
        th.text-center
          = t(:status)  
        th.text-center
          = t(:actions)  
    tbody
      - @ads.each do |ad|
        tr
          td.text-center
            = ad.title
          td.text-center
            = truncate(ad.description, :length => 30)
          - unless params[:action] == "user_ads"  
            td.text-center
              = ad.user.email
          td.text-center
            = ad.ad_type.name
          td.text-center
            = ad.status  
          td.text-center
            = link_to t(:show), ad, class: 'btn btn-sm btn-primary'
            - if can? :update, ad
              = link_to t(:edit), edit_ad_path(ad), class: 'btn btn-sm btn-primary'
            - if can? :destroy, ad
              = link_to t(:delete), ad, method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-sm btn-danger'
            - if can? :status_new, ad
              = link_to t(:send_for_moderation), status_new_ad_path(ad), method: :put, data: { confirm: t(:are_you_sure_new) }, class: "btn btn-sm btn-success"
            - if can? :status_draft, ad  
              = link_to t(:to_draft), status_draft_ad_path(ad), method: :put, data: { confirm: t(:are_you_sure_draft) }, class: "btn btn-sm btn-success"
  .digg_pagination.text-center
    = will_paginate @ads, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, :container => false   
- else
  h2.text-center
    = t(:the_list_is_empty)
  p.text-center
    = t("you_can_add_new")
    = link_to 'Here', new_ad_path, class: 'btn btn-sm btn-success'             

app/views/ads/_search-results.js.erb
$("#ads-table").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/ads/_search_and_filter.html.slim
.col-md-4
  .text-left[style="margin-top: 20px"]
    = form_tag(path, method: "get", remote: true, class: 'form-inline') do
      = hidden_field_tag :direction, params[:direction]
      = hidden_field_tag :sort, params[:sort]
      = label_tag(:search, t(:search))
      = text_field_tag :query, params[:query], label: t(:search_by_published), class: 'form-control', placeholder: t(:search_placeholder)
      = submit_tag t(:query_submit), class: 'btn btn-sm btn-success'
.col-md-4
  .text-left[style="margin-top: 20px"]
    = search_form_for @filter, url: path, remote: true, builder: SimpleForm::FormBuilder, wrapper: :horizontal_form, html: { class: 'form-inline'} do |f|
      = label_tag(:ad_type_id_eq, t(:choose_ad_type))
      = f.input :ad_type_id_eq, collection: AdType.all, required: false, label: false
      = f.button :submit, t(:filter_submit), class: 'btn btn-sm btn-success'

app/views/ads/edit.html.slim
.row
  .col-md-4.col-md-offset-4
    .panel.panel-primary
      .panel-heading.text-center
        h2.text-center
          = t(:edit_ad)
      .panel-body
        = render('form')
| > 

app/views/ads/index.html.slim
.row
  .col-md-8.col-md-offset-2
    .panel.panel-success
      .panel-heading
        .row
          .col-md-4
            h3.text-center
              = t(:published_ads)
          = render "search_and_filter", path: ads_path
      .panel-body
        #search-results
          = render("results")
        
          
        

app/views/ads/index.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/ads/new.html.slim
.row
  .col-md-4.col-md-offset-4
    .panel.panel-primary
      .panel-heading.text-center
        h2.text-center
          = t(:new_ad)
      .panel-body
        = render('form')
| > 

app/views/ads/show.html.slim
.container
  .jumbotron
    h1.text-center
      = @ad.title
    p
      = @ad.description
    hr.my-4
    - if @ad.images.attached?
      p.text-center
        strong
          = t(:images)
        br
      .text-center
        - @ad.images.each do |image|
          = image_tag image.variant(resize: "180x180")
    - else
      h3.text-center
        = t(:no_images)
      hr.my-4
    .text-center[style="margin-bottom: 20px"]
      span.label.label-lg.label-primary
        = t(:update)
        = @ad.updated_at.strftime("%b %d, %Y")
      span.label.label-lg.label-warning
        = t(:ad_type)
        = @ad.ad_type.name
      span.label.label-lg.label-success
        = t(:email)
        = @ad.user.email
    .text-center
      - if can? :update, @ad
        = link_to t(:edit), edit_ad_path(@ad), class: "btn btn-lg btn-warning"
      = link_to t(:back), :back, class: "btn btn-lg btn-primary"

app/views/ads/user_ads.html.slim
.row
  .col-md-8.col-md-offset-2
    .panel.panel-success
      .panel-heading.text-center
        .row
          .col-md-4
            h2.text-center
              = t(:my_ads)
          = render "search_and_filter", path: user_ads_ads_path
      .panel-body
        #search-results
          = render("results")

app/views/ads/user_ads.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/ads/user_archive.html.slim
.row
  .col-md-8.col-md-offset-2
    .panel.panel-success
      .panel-heading.text-center
        .row
          .col-md-4
            h2.text-center
              = t(:my_archived_ads)
          = render 'search_and_filter', path: user_archive_ads_path
      .panel-body
        #search-results
          = render("results")

app/views/ads/user_archive.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/layouts/_navigation.html.slim
header
  nav.navbar.navbar-default
    .container
      .navbar-header
        p.navbar-brand
          | The Advertising Project
      #navbar
        ul.nav.navbar-nav.navbar-left
          li
            p.navbar-btn
              = link_to t(:nav_main), root_path, class: 'btn btn-warning'
          - if current_user && current_user.admin
            li
              p.navbar-btn
                = link_to t(:nav_admin_panel), rails_admin.dashboard_path, class: 'btn btn-success'
          - if can? :user_ads, Ad
            li
              p.navbar-btn
                = link_to t(:nav_my_ads), user_ads_ads_path, class: 'btn btn-warning'
          - if can? :user_archive, Ad
            li
              p.navbar-btn
                = link_to t(:nav_archive), user_archive_ads_path, class: 'btn btn-warning'
          - if current_user && !current_user.admin
            li
              p.navbar-btn
                = link_to t(:new_ad), new_ad_path, class: 'btn btn-success'
        ul.nav.navbar-nav.navbar-right
          - if I18n.locale == :en
            li
              = link_to 'RU', locale: :ru
          - else I18n.locale == :ru
            li
              = link_to 'EN', locale: :en
          - if user_signed_in?
            li
              p.navbar-text
                = current_user.email
            li
              p.navbar-btn
                = link_to t(:edit_profile), edit_user_registration_path, class: 'btn btn-success'
            li
              p.navbar-btn
                = link_to t(:sign_out), destroy_user_session_path, class: 'btn btn-danger'
          - else
            li
              p.navbar-text
                = t(:please_sign_in_up)
            li
              p.navbar-btn
                = link_to t(:sign_in), new_user_session_path, class: 'btn btn-success'
            li
              p.navbar-btn
                = link_to t(:sign_up), new_user_registration_path, class: 'btn btn-primary'
      

                    

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Advertising Project
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navigation'
    = yield